### PR TITLE
Update Linux site for Pale Moon 28

### LINKED ISSUE #1: Update Linux site for Pale Moon 28
- [x] Remove the pminstaller tool.
- [x] Remove other relevant pminstaller code.
- [x] Update third party builds list (SSE-only is no longer maintained).
- [x] Update system requirements (and move to downloads page).
- [x] Update downloads page.
- [x] Review the FAQ page and update as needed.
- [x] Review and update the Manual Installation page.
- [ ] Publish.
- [x] Update build instructions (on developer wiki).

### PR DESCRIPTION
**Pull request by trav90**
Requesting review before publishing the changes. Also putting on hold until Pale Moon 28 is officially released.

Resolves #1.

### CODE REVIEW

**Comment by mattatobin** [comment]
Be sure to hit `artemis/components/site/site.php`

**Comment by trav90** [comment]
Thanks Tobin!

I added an additional commit to cleanup the remaining installer bits.

**Comment by mattatobin** [comment]
It looks ok to me but I won't know until you do it live.

**Comment by trav90** [comment]
Understood. I'll jump in IRC before I go live with it.

**Pull request merged**
